# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Justray < Formula
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"
  version "1.0.1"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luynrs/justray/releases/download/v1.0.1/justray_1.0.1_darwin_amd64.tar.gz"
      sha256 "4a6dfb1909e8a568d375824b7b09e21b7f86f808718c488594786903361f28a4"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luynrs/justray/releases/download/v1.0.1/justray_1.0.1_darwin_arm64.tar.gz"
      sha256 "0762cbbb4ec73b66e3744519d290d8306dfda6173224671f6ccf22c24831f265"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.0.1/justray_1.0.1_linux_amd64.tar.gz"
      sha256 "2c3b5e886b3193722e90ddc04116187835bed9da070b38413a0685f540192b01"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.0.1/justray_1.0.1_linux_arm64.tar.gz"
      sha256 "dfa2f85949db46aa334c7a05369dbcbd6f72dfef8be9970d5adead1b7fa6f0b2"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  test do
    system "#{bin}/justray", "--version"
  end
end
