# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Justray < Formula
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"
  version "1.2.1"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luynrs/justray/releases/download/v1.2.1/justray_1.2.1_darwin_amd64.tar.gz"
      sha256 "e9871afc11bcc265e634f50eb1b306240a367eb69597830fa1e0039a5d93baad"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luynrs/justray/releases/download/v1.2.1/justray_1.2.1_darwin_arm64.tar.gz"
      sha256 "d04eda2d0ef988e0c0744763038f869f676b584dbfe1b625632e4cffe13638ff"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.2.1/justray_1.2.1_linux_amd64.tar.gz"
      sha256 "f9aa808c3f6f38469e1198633330fd6bbc8be4e6585345ab8e3563083c2ae3f8"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.2.1/justray_1.2.1_linux_arm64.tar.gz"
      sha256 "51f62245ea3f4e2fe687c4d95e3a80ebaf1f5110bd7f0b10b4133d790312f037"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  test do
    system "#{bin}/justray", "--version"
  end
end
