# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Justray < Formula
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"
  version "1.1.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luynrs/justray/releases/download/v1.1.0/justray_1.1.0_darwin_amd64.tar.gz"
      sha256 "a1dc6bad6247a53ab9f07ef9f221260a2414d4088adf671c993790966355e1f9"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luynrs/justray/releases/download/v1.1.0/justray_1.1.0_darwin_arm64.tar.gz"
      sha256 "44832ea431feab0ff747899b9d0d315beb291dbb50cd1b3d0a6a40477cbc3cb6"

      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.1.0/justray_1.1.0_linux_amd64.tar.gz"
      sha256 "689e926269989d58bd0701f5ebc5fbf5d52d4849da9e88f519f26855c3b69ec7"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luynrs/justray/releases/download/v1.1.0/justray_1.1.0_linux_arm64.tar.gz"
      sha256 "9cf594c4395bed2c95516c4976be537a08f65b0f13de9c52625f97aeb47687d2"
      define_method(:install) do
        bin.install "justray"
        bin.install "justrayd"
        bin.install_symlink "justray" => "jray"
      end
    end
  end

  test do
    system "#{bin}/justray", "--version"
  end
end
