# This file was generated by GoReleaser. DO NOT EDIT.
cask "justray" do
  version "1.4.5"

  on_macos do
    on_arm do
      sha256 "c3d92932fe81f2a9b0dc27c108dda6492d3010efd4821ace028fbe17e943e2e7"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "775ae455a62e317e2edc3ab30541c13a2fe9b7100ed47b28dcd7dec3c718d572"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d8f224eeeeb5676bdf1f0abd7e445629e4fe0aba8e0e900c5ddc74ee8bd3758"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd9c7a5ab5ca4ff389532da9322a9e8f39becf81eaa1ce0cea510331f2046db9"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_amd64.tar.gz"
    end
  end

  name "justray"
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "justray"
  binary "justrayd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/justray", "#{staged_path}/justrayd"]
    end
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/justray", "#{HOMEBREW_PREFIX}/bin/jray"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/jray"
  end

  # No zap stanza required
end
