# This file was generated by GoReleaser. DO NOT EDIT.
cask "justray" do
  version "1.4.2"

  on_macos do
    on_arm do
      sha256 "becb2a90c2827356b79357b6711296247e76f809ee832f7255448413d19010b7"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5a9713e09cd5e77a051ddd7b4187fd0424682cb9e39b2eba681e2534590e148"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d9612c58f662971ef03f85ceed178093047cd68dd01f3398adaaaae68e0367f"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e603c333dfd2e10cadd48c551793262063d946c4d1073bc48a759e2f9e105c8"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_amd64.tar.gz"
    end
  end

  name "justray"
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "justray"
  binary "justrayd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/justray", "#{staged_path}/justrayd"]
    end
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/justray", "#{HOMEBREW_PREFIX}/bin/jray"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/jray"
  end

  # No zap stanza required
end
