# This file was generated by GoReleaser. DO NOT EDIT.
cask "justray" do
  version "1.5.1"

  on_macos do
    on_arm do
      sha256 "2ec3f742d4aadd251feb0dfc6e655b6a11925ea40c38eae9ba97fe1f65a95b7e"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7aea01f4ed8d2ad9b69a98ec76608adaf126933aa9b094ce60991b0af6ea32a8"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b7bc416b19401636afe24e7d15621ca75712f79bdda9ac19aa67f2d4d7f5807"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f3de37a5de9d26121ee3de254145e589db8b799685e900d976ad90ac2832c4bf"
      url "https://github.com/luynrs/justray/releases/download/v#{version}/justray_#{version}_linux_amd64.tar.gz"
    end
  end

  name "justray"
  desc "A modern VPN client that lives in your terminal"
  homepage "https://github.com/luynrs/justray"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "justray"
  binary "justrayd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/justray", "#{staged_path}/justrayd"]
    end
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/justray", "#{HOMEBREW_PREFIX}/bin/jray"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/jray"
  end

  # No zap stanza required
end
